export const ADD_BOOKS = 'ADD_BOOKS';
export const PATCH_BOOKS = 'PATCH_BOOKS';
export const DELETE_BOOKS = 'DELETE_BOOKS';
export const BOOKS_ERROR = 'BOOKS_ERROR';
export const BOOKS_REQUEST='@@BOOKS/BOOKS_REQUEST';
export const GET_BOOKS_SUCCESS='@@BOOKS/GET_BOOKS_SUCCESS';
export const BOOKS_FAILURE='@@BOOKS/BOOKS_FAILURE';