export const ADD_CHAPTERS = 'ADD_CHAPTERS';
export const PATCH_CHAPTERS = 'PATCH_CHAPTERS';
export const DELETE_CHAPTERS = 'DELETE_CHAPTERS';
export const CHAPTERS_ERROR = 'CHAPTERS_ERROR';
export const CHAPTERS_REQUEST='@@CHAPTERS/CHAPTERS_REQUEST';
export const GET_CHAPTERS_SUCCESS='@@CHAPTERS/GET_CHAPTERS_SUCCESS';
export const CHAPTERS_FAILURE='@@CHAPTERS/CHAPTERS_FAILURE';