export const ADD_MOVIES = 'ADD_MOVIES';
export const PATCH_MOVIES = 'PATCH_MOVIES';
export const DELETE_MOVIES = 'DELETE_MOVIES';
export const MOVIES_ERROR = 'MOVIES_ERROR';
export const MOVIES_REQUEST='@@MOVIES/MOVIES_REQUEST';
export const GET_MOVIES_SUCCESS='@@MOVIES/GET_MOVIES_SUCCESS';
export const MOVIES_FAILURE='@@MOVIES/MOVIES_FAILURE';