export const ADD_QUOTES = 'ADD_QUOTES';
export const PATCH_QUOTES = 'PATCH_QUOTES';
export const DELETE_QUOTES = 'DELETE_QUOTES';
export const QUOTES_ERROR = 'QUOTES_ERROR';
export const QUOTES_REQUEST='@@QUOTES/QUOTES_REQUEST';
export const GET_QUOTES_SUCCESS='@@QUOTES/GET_QUOTES_SUCCESS';
export const QUOTES_FAILURE='@@QUOTES/QUOTES_FAILURE';